// Custom Astro integration that wires stable `vite-plugin-pwa@1.3.0` into the
// build without taking a dependency on the preview `@serwist/astro` or the
// Astro-5-capped `@vite-pwa/astro`.
//
// The manifest is authored in `public/manifest.webmanifest` and is *not*
// generated by the plugin (`manifest: false`). The SW is registered manually
// from the authed layout via `workbox-window` (`injectRegister: false`) so it
// never ships to the landing page or auth pages.
//
// With `output: "server"`, Astro only runs Vite's SSR build — it never
// triggers a non-SSR build pass, so `vite-plugin-pwa`'s default `closeBundle`
// SW generation is skipped. We work around this by calling the plugin's
// public `generateSW()` method from the `astro:build:done` hook.

import type { AstroIntegration } from "astro";
import { VitePWA } from "vite-plugin-pwa";

export default function pwa(): AstroIntegration {
  let pwaPlugin: ReturnType<typeof VitePWA> | null = null;

  return {
    name: "bitworth-pwa",
    hooks: {
      "astro:config:setup": ({ updateConfig }) => {
        pwaPlugin = VitePWA({
          registerType: "autoUpdate",
          strategies: "generateSW",
          injectRegister: false,
          manifest: false,
          workbox: {
            // Astro's `output: "server"` runs the only Vite build with
            // outDir=dist/server/, so the plugin's default `swDest` would
            // land in dist/server/. Override to dist/client/ where the
            // Cloudflare `assets` binding actually serves static files.
            swDest: "dist/client/sw.js",
            globDirectory: "dist/client/",
            globPatterns: ["**/*.{js,css,html,png,svg,ico,webp,avif,webmanifest}"],
            // Exclude the pre-existing Capacitor/iOS/Android icon dump in
            // public/icons/app_icons/ — it's not served at runtime, and
            // including it would bloat the precache by ~30 files.
            globIgnores: ["**/app_icons/**", "**/sw.js", "**/workbox-*.js"],
            cleanupOutdatedCaches: true,
            navigateFallback: "/offline.html",
            navigateFallbackDenylist: [/^\/api\//, /^https:\/\/.*\.supabase\.co\//],
            runtimeCaching: [
              {
                urlPattern: ({ url }) =>
                  url.pathname.startsWith("/icons/") ||
                  url.pathname === "/favicon.png" ||
                  url.pathname === "/apple-touch-icon.png",
                handler: "CacheFirst",
                options: {
                  cacheName: "bitworth-static-assets",
                  expiration: { maxEntries: 20, maxAgeSeconds: 30 * 24 * 60 * 60 },
                },
              },
              {
                urlPattern: ({ url }) => url.pathname.startsWith("/_astro/"),
                handler: "StaleWhileRevalidate",
                options: {
                  cacheName: "bitworth-astro-assets",
                  expiration: { maxEntries: 50, maxAgeSeconds: 7 * 24 * 60 * 60 },
                },
              },
            ],
          },
          devOptions: {
            enabled: false,
            type: "module",
          },
        });
        updateConfig({
          vite: {
            plugins: [pwaPlugin],
          },
        });
      },
      "astro:build:done": async () => {
        if (!pwaPlugin) {
          throw new Error("[pwa] plugin reference is null");
        }
        // `VitePWA(...)` returns a 5-element plugin array. The first entry is
        // the MainPlugin, which exposes the public API (`generateSW`,
        // `extendManifestEntries`, `webManifestData`, ...) via the Vite
        // plugin's `api` property. The default `closeBundle` hook on the
        // BuildPlugin only runs when Vite's non-SSR build fires — and
        // Astro's `output: "server"` never triggers a non-SSR build pass, so
        // we have to drive it from `astro:build:done`. The type isn't
        // exported, so we cast.
        const mainPlugin = pwaPlugin[0] as unknown as {
          api?: { generateSW?: () => Promise<void> };
        };
        const api = mainPlugin.api;
        if (!api || typeof api.generateSW !== "function") {
          throw new Error("[pwa] api.generateSW missing on MainPlugin");
        }
        await api.generateSW();
      },
    },
  };
}
